    window.KAERI_MENU = [
        {
            id: 'intro',
            name: 'KAERI 소개',
            baseSize: 368,
            hoverSize: 550,
            posX: 48.2,
            posY: 61.0,
            baseColor: '#E9E9E9',
            hoverColor: '#6C63FF',
            hoverText: '연구원을 소개합니다',
            textColor: '#FFFFFF',
            href: '#intro',
            connected: true
        },
        {
            id: 'news',
            name: '보도자료',
            baseSize: 423,
            hoverSize: 550,
            posX: 6.8,
            posY: 91.8,
            baseColor: '#E9E9E9',
            hoverColor: '#A2A2A2',
            hoverText: '최신 연구소식',
            textColor: '#FFFFFF',
            href: '#news',
            connected: true
        },
        {
            id: 'safety',
            name: '안전정보',
            baseSize: 300,
            hoverSize: 375,
            posX: 80.7,
            posY: 36.6,
            baseColor: '#E9E9E9',
            hoverColor: '#FAAD69',
            hoverText: '안전을 최우선으로',
            textColor: '#FFFFFF',
            href: '#safety',
            connected: true
        },
        {
            id: 'rnd',
            name: '연구개발',
            baseSize: 300,
            hoverSize: 375,
            posX: 75.3,
            posY: 80.6,
            baseColor: '#E9E9E9',
            hoverColor: '#F0B3F9',
            hoverText: '미래 원자력 기술',
            textColor: '#1A1A1A',
            href: '#rnd',
            connected: true
        },
        {
            id: 'visit',
            name: '방문신청',
            baseSize: 300,
            hoverSize: 375,
            posX: 95.0,
            posY: 92.3,
            baseColor: '#E9E9E9',
            hoverColor: '#EB5757',
            hoverText: '견학을 신청하세요',
            textColor: '#FFFFFF',
            href: '#visit',
            connected: true
        },
        {
            id: 'customer',
            name: '고객참여',
            baseSize: 272,
            hoverSize: 340,
            posX: 3.4,
            posY: 50.3,
            baseColor: '#E9E9E9',
            hoverColor: '#2F80ED',
            hoverText: '국민과 함께합니다',
            textColor: '#FFFFFF',
            href: '#customer',
            connected: true
        },
        {
            id: 'region',
            name: '지역협력',
            baseSize: 211,
            hoverSize: 264,
            posX: 20.1,
            posY: 32.2,
            baseColor: '#E9E9E9',
            hoverColor: '#2D9CDB',
            hoverText: '지역사회와 함께',
            textColor: '#FFFFFF',
            href: '#region',
            connected: false
        },
        {
            id: 'achievement',
            name: '연구성과',
            baseSize: 186,
            hoverSize: 232.5,
            posX: 28.9,
            posY: 58.6,
            baseColor: '#E9E9E9',
            hoverColor: '#4EBC7D',
            hoverText: '주요 연구성과',
            textColor: '#FFFFFF',
            href: '#achievement',
            connected: false
        },
        {
            id: 'edu',
            name: '원자력교육센터',
            baseSize: 255,
            hoverSize: 318.75,
            posX: 29.2,
            posY: 90.8,
            baseColor: '#E9E9E9',
            hoverColor: '#9AFFC4',
            hoverText: '교육 프로그램 안내',
            textColor: '#1A1A1A',
            href: '#edu',
            connected: false
        },
        {
            id: 'info',
            name: '정보공개',
            baseSize: 216,
            hoverSize: 270,
            posX: 59.4,
            posY: 31.7,
            baseColor: '#E9E9E9',
            hoverColor: '#4F4F4F',
            hoverText: '투명한 정보 제공',
            textColor: '#FFFFFF',
            href: '#info',
            connected: true
        },
        {
            id: 'tech',
            name: '기술이전',
            baseSize: 208,
            hoverSize: 260,
            posX: 66.1,
            posY: 57.6,
            baseColor: '#E9E9E9',
            hoverColor: '#738AC3',
            hoverText: '연구성과를 산업으로',
            textColor: '#FFFFFF',
            href: '#tech',
            connected: false
        },
        {
            id: 'recruit',
            name: '채용정보',
            baseSize: 228,
            hoverSize: 285,
            posX: 60.4,
            posY: 93.3,
            baseColor: '#E9E9E9',
            hoverColor: '#DDE2FF',
            hoverText: '함께할 인재 모집',
            textColor: '#1A1A1A',
            href: '#recruit',
            connected: false
        },
        {
            id: 'patent',
            name: '특허·사업화',
            baseSize: 152,
            hoverSize: 190,
            posX: 90.1,
            posY: 64.5,
            baseColor: '#E9E9E9',
            hoverColor: '#8D1E10',
            hoverText: '기술 사업화',
            textColor: '#FFFFFF',
            href: '#patent',
            connected: false
        },
        {
            id: 'video',
            name: '홍보영상',
            baseSize: 119,
            hoverSize: 148.75,
            posX: 18.2,
            posY: 72.8,
            baseColor: '#E9E9E9',
            hoverColor: '#313131',
            hoverText: 'KAERI TOUR',
            textColor: '#FFFFFF',
            href: '#video',
            connected: false
        },
        {
            id: 'sns',
            name: 'SNS',
            baseSize: 99,
            hoverSize: 123.75,
            posX: 33.1,
            posY: 32.2,
            baseColor: '#E9E9E9',
            hoverColor: '#FFFF98',
            hoverText: 'KAERI 채널',
            textColor: '#1A1A1A',
            href: '#sns',
            connected: false
        }
    ];

